[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "cd client && npm install --legacy-peer-deps",
  "cd client && DISABLE_ESLINT_PLUGIN=true CI=false npm run build"
]

[start]
cmd = "npm start"
