[variables]
CI = "false"
DISABLE_ESLINT_PLUGIN = "true"
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["cd client && npm install --legacy-peer-deps && npm run build"]

[start]
cmd = "npm start"
